apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yoa7wu4zm-nodejs 
  janus-idp.io/tekton: yoa7wu4zm-nodejs
  backstage.io/kubernetes-id: yoa7wu4zm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yoa7wu4zm-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  