apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: yoa7wu4zm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yoa7wu4zm-nodejs 
  name: yoa7wu4zm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: yoa7wu4zm-nodejs 
